// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddBookingWorksController from "./add_booking_works_controller"
application.register("add-booking-works", AddBookingWorksController)

import ClientSearchController from "./client_search_controller"
application.register("client-search", ClientSearchController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
